name: Shell

on:
  push:
    paths:
      - '/*'
      - '.github/workflows/shell.yml'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -s sh
