name: Shell

on:
  push:
    paths:
      - '*.sh'

permissions: {}

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -s sh
  output:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
          sudo apt-get install -yq lolcat figlet
      - run: sh essentials.sh

