name: Shell

on:
  push:
    paths:
      - '*.sh'
      - '.github/workflows/shell.yml'

permissions: {}

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -s sh
  output:
    needs: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          sudo apt-get update
          sudo apt-get install -yq lolcat figlet
      - run: sh essentials.sh

